/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { PetLiquidFlattenInrtManager } from "./PetLiquidFlattenInrtManager";

export class PetLiquidFlattenInrtManagerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PetLiquidFlattenInrtManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PetLiquidFlattenInrtManager;
  }
}

const _abi = [
  {
    inputs: [],
    name: "addToBurnPool",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "addToLuckPool",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentNrtMonth",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
